# Generated by Django 6.0.7 on 2026-07-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True, max_length=100)),
            ],
        ),
    ]
