# Generated by Django 6.0.7 on 2026-07-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.CharField(max_length=5)),
                ('section', models.CharField(max_length=5)),
                ('room_no', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
