# Generated by Django 6.0.7 on 2026-08-03 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_class_alter_teachers_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.CharField(max_length=5)),
                ('section', models.CharField(max_length=5)),
                ('room_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.RemoveField(
            model_name='students',
            name='course',
        ),
        migrations.AddField(
            model_name='students',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='my_app.schoolclass'),
        ),
    ]
