# Generated by Django 6.0.7 on 2026-08-03 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_schoolclass_delete_class_remove_students_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_app.schoolclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_app.teachers')),
            ],
        ),
    ]
