# Generated by Django 6.0.7 on 2026-08-04 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_attendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(choices=[('MID', 'Mid Term'), ('FINAL', 'Final Term')], max_length=35)),
                ('obtain_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_app.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_app.subjects')),
            ],
        ),
    ]
